services:
  ms-notification:
    build:
      context: .
      args:
        BUILDPLATFORM: linux/arm64
    platform: linux/arm64
    ports:
      - "8010:8010"
    networks:
      - gateway-network

networks:
  gateway-network:
    external: true